stages:
  - test
  - build
  - manifest

variables:
  BASE_IMAGE_TAG: "26.04@sha256:6df9e8dd1eac389ebfef692c9648449adeb815d01e16e29cd6f3e50fe64ba9a6"
  UBUNTU_VERSION: "26.04"
  FF_NETWORK_PER_BUILD: "true"

.base_job: &base_job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    # No suffix for default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/review@0.9.0

build:
  <<: *base_job
  stage: build
  needs: []
  image: docker:latest@sha256:12e683a161823b2a839aeea999b9d960e6e1f9a97b1679ad6b441982e2d9cf07
  tags:
    - $RUNNER_TAG
  script:
    - apk add bash
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
      docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}";
      fi
    - ./bin/build.sh
  parallel:
    matrix:
      - ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  stage: manifest
  needs: [build]
  image: docker:latest@sha256:12e683a161823b2a839aeea999b9d960e6e1f9a97b1679ad6b441982e2d9cf07
  tags:
    - thelab-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - apk add bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/push-manifest.sh
