stages:
  - build
  - manifest

variables:
  BASE_IMAGE_TAG: "24.04@sha256:d1e2e92c075e5ca139d51a140fff46f84315c0fdce203eab2807c7e495eff4f9"
  UBUNTU_VERSION: "24.04"
  FF_NETWORK_PER_BUILD: "true"

.base_job: &base_job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    # No suffix for default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

build:
  <<: *base_job
  stage: build
  image: docker:latest@sha256:68f6d9ab84623d1116c5432a3b924a07ee09960e6129ca1cb03ef14010588cb4
  tags:
    - $RUNNER_TAG
  script:
    - apk add bash
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
      docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}";
      fi
    - ./bin/build.sh
  parallel:
    matrix:
      - ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  stage: manifest
  needs: [build]
  image: docker:latest@sha256:68f6d9ab84623d1116c5432a3b924a07ee09960e6129ca1cb03ef14010588cb4
  tags:
    - thelab-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - apk add bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/push-manifest.sh
